"""Initial migration

Revision ID: ede40aee8750
Revises: 
Create Date: 2025-03-21 12:40:04.311561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede40aee8750'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shorten_links',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('url', sa.String, unique=True),
        sa.Column('short_link', sa.String, unique=True),
        sa.Column('creation_date', sa.DateTime, nullable=False),
        sa.Column('last_use_date', sa.DateTime),
        sa.Column('expires_at', sa.DateTime),
        sa.Column('user_id', sa.String, nullable=True),
    )
    op.create_table(
        'user',
        sa.Column('id', sa.UUID, primary_key=True, index=True),
        sa.Column('email', sa.String, nullable=False),
        sa.Column('hashed_password', sa.String, nullable=False),
        sa.Column('registered_at', sa.TIMESTAMP, server_default=sa.func.now()),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('is_superuser', sa.Boolean, default=True, nullable=False),
        sa.Column('is_verified', sa.Boolean, default=True, nullable=False),
    )
    
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shorten_links', sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shorten_links', sa.Column('clicks_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('shorten_links_alias_key', 'shorten_links', ['alias'])
    op.drop_column('shorten_links', 'user_id')
    # ### end Alembic commands ###
