version: "3.7"
services:
  db:
    image: postgres:17
    container_name: db_app
    environment:
      POSTGRES_PASSWORD: 13111730
      POSTGRES_USER: postgres
      POSTGRES_DB: shortening_links_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shortening_links_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    expose:
      - 5432

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
      